# Generated by Django 5.0.7 on 2024-08-06 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconvenience_allowance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inconveniencerequestline',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='inconveniencerequestline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inconveniencerequest',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inconveniencerequest',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_manager_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='no_of_ph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='no_of_weekend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
