# Generated by Django 5.0.7 on 2024-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconvenience_allowance', '0002_remove_inconveniencerequestline_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
