# Generated by Django 5.0.7 on 2024-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconvenience_allowance', '0003_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inconveniencerequestline',
            name='response',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
